### ISSUE TITLE
First word missing (?) in short description

### ISSUE THREAD

**Issue by dajare** [standardebooks/will-james_smoky-the-cowhorse#2]
The short [description line][a] in `content.opf` looks like this:

```
<dc:description id="description">, a gray-colored horse, grows into adulthood on the ranges of the American West.</dc:description>
```

leaving us with:

> , a gray-colored horse, grows into adulthood on the ranges of the American West.

for the short description. SOMEthing has dropped out! Is it "Smoky"? Or should it read: "A gray-colored horse..."?

[a]: https://github.com/standardebooks/will-james_smoky-the-cowhorse/blob/75b51929600e0e90791a9b81d703e85ee4b613f8/src/epub/content.opf#L47

**Comment by acabal** [comment]
This should be fixed now, thanks!
